<a href="https://colab.research.google.com/github/Prithvi0615/PRITHVI_EDA_0/blob/main/prithvi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s= pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values #to get the values of the dataset

array([10, 20, 30, 40, 50])

In [ ]:
s.index #to get the index position of the dataset

RangeIndex(start=0, stop=5, step=1)

In [ ]:
import pandas as pd
s = pd.Series([10,20,30,40,50])
print(s.name) # .name to represent the name of the table that we created in pandas

None

In [ ]:
s.name= "calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [ ]:
s[2:4] #to perform slicing

2    30
3    40
Name: calories, dtype: int64

In [ ]:
#iloc -> location based indexingh
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [ ]:
index= ["apple","banana","grapes","orange","strawberry"]

In [ ]:
s.index =index #s.index will be used to perform some values to the index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
s.iloc[3]

np.int64(40)

In [ ]:
#iloc-> label based indexing
s.loc[['grapes','apple']] #we can perform mutliple indexing inside this

KeyError: "None of [Index(['grapes', 'apple'], dtype='object')] are in the [index]"

In [ ]:
#in label indexing yor start as well as as stop value both are included in output
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [ ]:
fruit_protein = {
    "Avocado":2.0,
    "Guava":2.6,
    "Blackberries":2.0,
    "Oranges":0.9,
    "Banana":1.1,
    "Apple":0.3,
    "Kiwi":1.1,
    "Pomegranate":1.7,
    "Mango":0.8,
    "Cherries":1.0
}

In [ ]:
import pandas as pd
s2 = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# Logical indexing to display values greater than 1
s2[s2 > 1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

In [ ]:
# Using the logical 'not' operator
s2[~(s2 > 1)]

Oranges     0.9
Apple       0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

In [ ]:
# Using the logical 'and' operator
s2[(s2 > 0.5) | (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apple           0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [ ]:
# Using the logical 'and' operator
s2[(s2 > 0.5) & (s2 <= 2)]

Avocado         2.0
Blackberries    2.0
Oranges         0.9
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64